name: InfiniPlots
version: '${version}'
main: me.whizvox.infiniplots.InfiniPlots
api-version: '1.20'
author: whizvox
description: Plots plugin
softdepend:
  - WorldGuard
commands:
  infiniplots:
    description: General command for InfiniPlots
    aliases:
      - plots
      - infp